### ISSUE TITLE
Is HumidityCheck.php still being maintained?

### ISSUE THREAD

**Issue by rr0ss0rr** [rbrenton/nest-utils#1]
Hi there .. I was looking for a way to modify the humidity based on outside temp and came across your code?  Any issues?    Just a quick scan and noticed the following .. I think you meant "heat"?

} else if($mode=='head') {
    $cool = null;
  } else {
    $cool = $head = null;

**Comment by rbrenton** [comment]
Hello!

The main issue is the accuracy of the humidity sensors on the nest thermostats.  I just pushed a commit with the most recent code.  I have 2 thermostats so I started using the second one to sanity check inside dewpoints.  I also added an additional outside data source for my wunderground station.  It looks like the typos you found are fixed in the latest code.

Enjoy!

-Brenton

**Comment by klasenby** [comment]
I used this script last year with my Nest and found it worked great for "reasonable" winter temperatures (+5C to -7 C) but when it got down to -10C to -30C it was way too aggressive and I got a lot of condensation on my windows.  

To get around these issues I hard-coded temperature ranges into the script: https://github.com/klasenby/nest-utils/blob/master/simpleHumiditySet.php

I'll give your new build a try in a few months when it gets cold again!  I really wish Nest would build this logic into their own code.

Kevin

**Comment by rbrenton** [comment]
@klasenby 

I just noticed your fork and was looking for anything I could pull upstream.  I'll be using it again this winter so I'm sure I'll be tweaking it.  Now that I know others are using it I'll try to keep the code more up to date.

I've found that the nest sensors are pretty horrible (at least dewpoint/humidity), and you need a hyper local outdoor dewpoint sensor too.  I have some ideas to improve on it, but there's only so much you can do without adding more hardware.

Thanks for the feedback!

-Brenton

**Comment by klasenby** [comment]
I'm definitely using it and am looking for ways to make it better; a few of my friends are using it as well.  I'm up for trying a separate humidity sensor or two, maybe something cheaper than a 2nd thermostat?  I'll see what I can find for sensors and if there's an easy way to include their data.
Kevin

Date: Mon, 29 Aug 2016 07:52:11 -0700

**Comment by rbrenton** [comment]
@klasenby awesome!  Keep me posted!

I have some 433mhz sensors and an arduino project that listens to them and just displays them on an LCD.  I don't think I have it published anywhere, yet.  I'm keen to use something like that and just extend it, but happy to see the project extended to use other data sources; especially where an API may already exist.

-Brenton
