### ISSUE TITLE
Wunderground station

### ISSUE THREAD

**Issue by rr0ss0rr** [rbrenton/nest-utils#2]
Thanks .. Your code is a lot more sophisticated than what I was using (forcing humidity level based on the Recommended Indoor Relative Humidity guide) and I do prefer yours.  I added a Wunderground station close to me .. but looks like every now and then I have an issue with target humidity being set to 10%

2016-08-29 15:08  THERMOSTAT(temp=77F, dewpoint=58.1F, humidity=52%, target=10%) - OUTSIDE(temp=75.9F, dewpoint=65F, humidity=69%) - OK

Update: I see that you have code to throttle the humidifier if insideDewpoint (58) >= MAX_DEWPOINT (46)

Of course it's summer and I wouldn't be running the script .. Just preparing .. Winter is Coming ;-)
Count be in on using the newly uploaded code.

Thanks again

**Comment by rbrenton** [comment]
Yeah, it is setting humidity to 10% to basically disable humidification.  Glad you got it figured out, and thanks for the feedback!

For anyone else that stumbles on this, the placeholder for the wunderground station is it's identifier and not the API key.

-Brenton
